from typing import List

from pydantic import BaseModel, Field


class ResearchReport(BaseModel):
    """
    Structured report generated by the Research Agent.

    The Research Agent enriches an EventReport with
    pharmaceutical supply-chain intelligence gathered
    from external sources.

    This report is consumed by the Risk Assessment Agent.
    """

    # ======================================================
    # Original Event Information
    # ======================================================

    headline: str = Field(
        description="Headline of the original event."
    )

    event_type: str = Field(
        description="Category of the detected event."
    )

    event_summary: str = Field(
        description="Summary of the original event."
    )

    location: str | None = Field(
        default=None,
        description="Primary affected location."
    )

    # ======================================================
    # Research Summary
    # ======================================================

    research_summary: str = Field(
        description=(
            "Concise summary of the pharmaceutical "
            "supply-chain findings."
        )
    )

    # ======================================================
    # Geographic Impact
    # ======================================================

    affected_regions: List[str] = Field(
        default_factory=list,
        description="Regions potentially affected."
    )

    affected_countries: List[str] = Field(
        default_factory=list,
        description="Countries potentially affected."
    )

    # ======================================================
    # Logistics
    # ======================================================

    affected_trade_routes: List[str] = Field(
        default_factory=list,
        description="Trade routes affected."
    )

    affected_ports: List[str] = Field(
        default_factory=list,
        description="Ports affected."
    )

    # ======================================================
    # Pharmaceutical Industry
    # ======================================================

    affected_manufacturers: List[str] = Field(
        default_factory=list,
        description="Potentially affected pharmaceutical manufacturers."
    )

    affected_api_suppliers: List[str] = Field(
        default_factory=list,
        description="Potentially affected API suppliers."
    )

    affected_raw_materials: List[str] = Field(
        default_factory=list,
        description="Potentially affected raw materials."
    )

    # ======================================================
    # Supporting Evidence
    # ======================================================

    evidence: List[str] = Field(
        default_factory=list,
        description="Important factual evidence collected from research."
    )

    web_sources: List[str] = Field(
        default_factory=list,
        description="URLs used during research."
    )

    # ======================================================
    # Confidence
    # ======================================================

    confidence: float = Field(
        ge=0.0,
        le=1.0,
        description="Confidence score between 0 and 1."
    )