from typing import List

from pydantic import BaseModel, Field


class RiskReport(BaseModel):
    """
    Final decision report generated by the Risk Assessment Agent.

    This report combines:

    • Risk Assessment
    • Pharmaceutical Impact
    • Recommended Actions

    It is intended to be displayed directly on the dashboard.
    """

    # =====================================================
    # Event Information
    # =====================================================

    headline: str = Field(
        description="Headline of the event."
    )

    event_type: str = Field(
        description="Category of the event."
    )

    location: str | None = Field(
        default=None,
        description="Primary affected location."
    )

    # =====================================================
    # Overall Risk
    # =====================================================

    overall_risk: str = Field(
        description=(
            "Overall pharmaceutical supply chain risk. "
            "Must be one of: LOW, MEDIUM, HIGH, CRITICAL."
        )
    )

    risk_score: int = Field(
        ge=0,
        le=100,
        description="Overall risk score between 0 and 100."
    )

    confidence: float = Field(
        ge=0.0,
        le=1.0,
        description="Confidence score between 0 and 1."
    )

    # =====================================================
    # Supply Chain Impact
    # =====================================================

    estimated_shortage_time: str = Field(
        description=(
            "Estimated time before medicine shortages "
            "could begin."
        )
    )

    affected_medicines: List[str] = Field(
        default_factory=list,
        description="Medicines likely to be affected."
    )

    affected_apis: List[str] = Field(
        default_factory=list,
        description="Active Pharmaceutical Ingredients likely to be affected."
    )

    affected_regions: List[str] = Field(
        default_factory=list,
        description="Regions expected to experience shortages."
    )

    # =====================================================
    # Recommendations
    # =====================================================

    recommended_actions: List[str] = Field(
        default_factory=list,
        description="Immediate actions recommended."
    )

    recommended_imports: List[str] = Field(
        default_factory=list,
        description="Medicines or APIs whose imports should be increased."
    )

    alternative_suppliers: List[str] = Field(
        default_factory=list,
        description="Suggested alternative sourcing regions or countries."
    )

    # =====================================================
    # Alerts
    # =====================================================

    hospital_alert: str = Field(
        description=(
            "Hospital alert level. "
            "Must be LOW, MEDIUM, HIGH or CRITICAL."
        )
    )

    government_actions: List[str] = Field(
        default_factory=list,
        description="Suggested actions for regulatory authorities."
    )

    # =====================================================
    # Explanation
    # =====================================================

    reasoning: str = Field(
        description=(
            "Brief explanation justifying the overall risk "
            "assessment and recommendations."
        )
    )